services:
  debian:
    build:
      context: .
    image: vimdev-debian:latest
    network_mode: host
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - tmux_resurrect:/root/.tmux/resurrect
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose/workdirs.txt:/root/.config/workdirs.txt
    stdin_open: true
    tty: true
    extra_hosts:
      - platform-local.getruck.co.il:127.0.0.1

volumes:
  tmux_resurrect:
