services:
  debian:
    build:
      context: .
    image: vimdev-debian
    pull_policy: never
    network_mode: host
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ovim:/root/.ovim
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose/workdirs.txt:/root/.config/workdirs.txt
      - ~/.ovim/.env:/root/.env:ro
      - tmux_resurrect:/root/.tmux/resurrect
    stdin_open: true
    tty: true

volumes:
  tmux_resurrect:
