services:
  debian:
    build:
      context: .
    image: omriashkenazi/ovim:1.1.0
    pull_policy: never
    network_mode: host
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - ~/.gitconfig:/root/.gitconfig
      - ~/.ovim:/root/.ovim
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose/workdirs.txt:/root/.config/workdirs.txt:ro
      - ~/.ovim/.env:/root/.env:ro
      #- tmux_resurrect:/root/.tmux/resurrect
      - bash_history:/root/.bash_history_data
    stdin_open: true
    tty: true

volumes:
  #tmux_resurrect:
  bash_history:
